spring.application.name=Lab08_SBA

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/SBA301DB
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# Server
server.port=8080

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp